# Generated by Django 2.1.5 on 2019-01-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=50, verbose_name='Curso')),
                ('carga_h', models.IntegerField(verbose_name='Carga Horária')),
                ('ementa', models.CharField(max_length=40, verbose_name='Ementa')),
                ('Valor', models.FloatField(verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_i', models.DateField(verbose_name='Data de Inicio')),
                ('data_t', models.DateField(verbose_name='Data de Término')),
                ('hora_i', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_t', models.TimeField(verbose_name='Hora de Termino')),
            ],
        ),
    ]
