# Generated by Django 2.1.5 on 2019-01-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.CharField(max_length=50)),
                ('tipo_despesa', models.CharField(choices=[('remedio', 'Remedio'), ('alimentação', 'Alimentação'), ('educação', 'Educação'), ('transporte', 'Transporte')], max_length=50)),
                ('descricao', models.CharField(max_length=40)),
                ('forma_pag', models.CharField(choices=[('1', 'Dinheiro'), ('2', 'Cartão de Crédito'), ('3', 'Cartão de Debito')], max_length=30)),
                ('vencimento', models.DateField()),
                ('quitato', models.BooleanField()),
            ],
        ),
    ]
