# Generated by Django 2.1.5 on 2019-01-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190117_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='quitado',
            field=models.BooleanField(verbose_name='Quitado'),
        ),
    ]
